version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Install cfn-lint & taskcat"
      - pip install cfn-lint taskcat

  pre_build:
    commands:
      - echo "Run cfn-lint"
      - cfn-lint template.yaml

  build:
    commands:
      - echo "Run taskcat"
      - taskcat test run

artifacts:
  files:
    - '**/*'
