version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install cfn-lint taskcat

  build:
    commands:
      - echo "Running cfn-lint..."
      - cfn-lint cloudformation/template.yaml

      - echo "Running taskcat..."
      - taskcat test run --config cloudformation/taskcat.yml

artifacts:
  files:
    - '**/*'
