AWSTemplateFormatVersion: '2010-09-09'
Description: NT548 Lab2 - CodePipeline with CodeBuild for CloudFormation (AWS Academy compatible)

Parameters:
  RepositoryName:
    Type: String
    Default: NT548-Lab2-CloudFormation

Resources:

  ### CodeBuild Project ###
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: NT548-Lab2-CodeBuild
      ServiceRole: arn:aws:iam::897284482706:role/LabRole
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      Source:
        Type: CODECOMMIT
        Location: !Sub https://git-codecommit.us-east-1.amazonaws.com/v1/repos/${RepositoryName}
        BuildSpec: cloudformation/buildspec.yml

  ### CodePipeline ###
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: NT548-Lab2-Pipeline
      RoleArn: arn:aws:iam::897284482706:role/LabRole
      ArtifactStore:
        Type: S3
        Location: !Sub nt548-lab2-artifacts-${AWS::AccountId}
      Stages:

        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: '1'
              Configuration:
                RepositoryName: !Ref RepositoryName
                BranchName: main
              OutputArtifacts:
                - Name: SourceOutput

        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject

        - Name: Deploy
          Actions:
            - Name: DeployCloudFormation
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName: NT548-Lab2-Infrastructure
                TemplatePath: SourceOutput::cloudformation/template.yaml
                Capabilities: CAPABILITY_NAMED_IAM
